language:
  - elixir

elixir:
  - 1.6

otp_release:
  - 20.0

sudo: false

cache:
  directories:
    - .dialyzer

script:
  - mix initialize
  - mix test
  - mix dialyzer
  - mix format --check-formatted
  - MIX_ENV=test mix do compile --warnings-as-errors, coveralls.json

after_success:
- bash <(curl -s https://codecov.io/bash)

notifications:
  email: false